### ISSUE TITLE
Pointers VS References

### ISSUE THREAD

**Issue by KJ-Panda** [theshamot/Higher-Level-TwinCAT-3-Library#1]
This might be a basic question, but why are lists using pointers in the node datatype instead of references? Is there some limitation of references which makes them unusable for this application, you're just used to pointers, compatability with TC2 systems or something else?

**Comment by theshamot** [comment]
Hello, I'm using pointers here because reference can only point to a variable of specific type. Here I'm allocating space in memory using __NEW() and pointer points to this location in memory. It does not point to a variable.

**Comment by KJ-Panda** [comment]
Ah, ok thanks.

**Comment by theshamot** [comment]
I just came home, so here is some more elaboration on the problem:
If we assume that twincat works similar to C, we can read in the following link that reference is just another name for variable. So we are not able to use references, because my linkedlist items are just some allocated memory and not variables

https://www.tutorialspoint.com/pointers-vs-references-in-cplusplus

**Comment by KJ-Panda** [comment]
Yeah I read a bit more of the code and it seems like I've got more to learn about flexible datatypes. Very exciting though, seems really powerful if used right (and powerfully system-crashing if used wrong 😁)
